import type { LoLGameParticipantChallenges } from '~/lib/types/match'

/**
 * Every field of `LoLGameParticipantChallenges`, used to
 * drive the raw stats table without hand-listing 122 rows twice.
 */
export const CHALLENGE_FIELD_KEYS: (keyof LoLGameParticipantChallenges)[] = [
  'oneTwoAssistStreakCount',
  'baronBuffGoldAdvantageOverThreshold',
  'controlWardTimeCoverageInRiverOrEnemyHalf',
  'earliestBaron',
  'earliestDragonTakedown',
  'earliestElderDragon',
  'earlyLaningPhaseGoldExpAdvantage',
  'fasterSupportQuestCompletion',
  'fastestLegendary',
  'hadAfkTeammate',
  'highestChampionDamage',
  'highestCrowdControlScore',
  'highestWardKills',
  'junglerKillsEarlyJungle',
  'killsOnLanersEarlyJungleAsJungler',
  'laningPhaseGoldExpAdvantage',
  'legendaryCount',
  'maxCsAdvantageOnLaneOpponent',
  'maxLevelLeadLaneOpponent',
  'mostWardsDestroyedOneSweeper',
  'mythicItemUsed',
  'playedChampSelectPosition',
  'soloTurretsLategame',
  'takedownsFirst25Minutes',
  'teleportTakedowns',
  'thirdInhibitorDestroyedTime',
  'threeWardsOneSweeperCount',
  'visionScoreAdvantageLaneOpponent',
  'infernalScalePickup',
  'fistBumpParticipation',
  'voidMonsterKill',
  'abilityUses',
  'acesBefore15Minutes',
  'alliedJungleMonsterKills',
  'baronTakedowns',
  'blastConeOppositeOpponentCount',
  'bountyGold',
  'buffsStolen',
  'completeSupportQuestInTime',
  'controlWardsPlaced',
  'damagePerMinute',
  'damageTakenOnTeamPercentage',
  'dancedWithRiftHerald',
  'deathsByEnemyChamps',
  'dodgeSkillShotsSmallWindow',
  'doubleAces',
  'dragonTakedowns',
  'effectiveHealAndShielding',
  'elderDragonKillsWithOpposingSoul',
  'elderDragonMultikills',
  'enemyChampionImmobilizations',
  'enemyJungleMonsterKills',
  'epicMonsterKillsNearEnemyJungler',
  'epicMonsterKillsWithin30SecondsOfSpawn',
  'epicMonsterSteals',
  'epicMonsterStolenWithoutSmite',
  'flawlessAces',
  'fullTeamTakedown',
  'gameLength',
  'goldPerMinute',
  'hadOpenNexus',
  'immobilizeAndKillWithAlly',
  'jungleCsBefore10Minutes',
  'junglerTakedownsNearDamagedEpicMonster',
  'kda',
  'killAfterHiddenWithAlly',
  'killParticipation',
  'killsNearEnemyTurret',
  'killsOnOtherLanesEarlyJungleAsLaner',
  'killsUnderOwnTurret',
  'killsWithHelpFromEpicMonster',
  'knockEnemyIntoTeamAndKill',
  'kTurretsDestroyedBeforePlatesFall',
  'landSkillShotsEarlyGame',
  'laneMinionsFirst10Minutes',
  'lostAnInhibitor',
  'maxKillDeficit',
  'mejaisFullStackInTime',
  'moreEnemyJungleThanOpponent',
  'multiKillOneSpell',
  'multikills',
  'multikillsAfterAggressiveFlash',
  'multiTurretRiftHeraldCount',
  'outerTurretExecutesBefore10Minutes',
  'outnumberedKills',
  'outnumberedNexusKill',
  'perfectDragonSoulsTaken',
  'perfectGame',
  'pickKillWithAlly',
  'poroExplosions',
  'quickCleanse',
  'quickFirstTurret',
  'riftHeraldTakedowns',
  'saveAllyFromDeath',
  'scuttleCrabKills',
  'skillshotsDodged',
  'skillshotsHit',
  'snowballsHit',
  'soloBaronKills',
  'soloKills',
  'stealthWardsPlaced',
  'survivedSingleDigitHpCount',
  'survivedThreeImmobilizesInFight',
  'takedownOnFirstTurret',
  'takedowns',
  'takedownsAfterGainingLevelAdvantage',
  'takedownsBeforeJungleMinionSpawn',
  'takedownsInEnemyFountain',
  'teamBaronKills',
  'teamDamagePercentage',
  'teamElderDragonKills',
  'teamRiftHeraldKills',
  'tookLargeDamageSurvived',
  'turretPlatesTaken',
  'turretsTakenWithRiftHerald',
  'turretTakedowns',
  'twentyMinionsIn3SecondsCount',
  'unseenRecalls',
  'visionScorePerMinute',
  'wardsGuarded',
  'wardTakedowns',
  'wardTakedownsBefore20M',
]

const CHALLENGE_FIELD_LABELS: Record<string, string> = {
  oneTwoAssistStreakCount: 'Série de 12 assists',
  baronBuffGoldAdvantageOverThreshold: "Avantage d'or (buff Baron)",
  controlWardTimeCoverageInRiverOrEnemyHalf:
    'Couverture balise de contrôle (rivière/camp ennemi)',
  earliestBaron: 'Baron le plus précoce',
  earliestDragonTakedown: 'Premier dragon pris le plus tôt',
  earliestElderDragon: 'Dragon ancien le plus précoce',
  earlyLaningPhaseGoldExpAdvantage: 'Avantage or/exp en début de phase de lane',
  fasterSupportQuestCompletion: 'Quête support terminée rapidement',
  fastestLegendary: 'Objet légendaire le plus rapide',
  hadAfkTeammate: 'Coéquipier AFK dans la partie',
  highestChampionDamage: 'Plus gros dégâts aux champions de la partie',
  highestCrowdControlScore: 'Meilleur score de contrôle de foule',
  highestWardKills: 'Plus de wards détruites',
  junglerKillsEarlyJungle: 'Kills en early jungle (jungler)',
  killsOnLanersEarlyJungleAsJungler:
    'Kills sur des laners en early jungle (jungler)',
  laningPhaseGoldExpAdvantage: 'Avantage or/exp en phase de lane',
  legendaryCount: 'Nombre de statuts légendaires',
  maxCsAdvantageOnLaneOpponent: "Avance CS max sur l'adversaire de lane",
  maxLevelLeadLaneOpponent: "Avance de niveau max sur l'adversaire de lane",
  mostWardsDestroyedOneSweeper: 'Plus de wards détruites avec un balai',
  mythicItemUsed: 'Objet mythique acheté',
  playedChampSelectPosition: 'Poste choisi en sélection de champion',
  soloTurretsLategame: 'Tourelles prises seul en fin de partie',
  takedownsFirst25Minutes: 'Éliminations dans les 25 premières minutes',
  teleportTakedowns: 'Éliminations après téléportation',
  thirdInhibitorDestroyedTime: 'Temps de destruction du 3e inhibiteur',
  threeWardsOneSweeperCount: '3 wards détruites avec un seul balai',
  visionScoreAdvantageLaneOpponent:
    "Avantage de score de vision sur l'adversaire de lane",
  infernalScalePickup: 'Écailles infernales ramassées',
  fistBumpParticipation: 'Participation aux checks de poing',
  voidMonsterKill: 'Monstres du néant tués',
  abilityUses: 'Sorts lancés',
  acesBefore15Minutes: 'Aces avant 15 minutes',
  alliedJungleMonsterKills: 'Monstres de sa jungle tués',
  baronTakedowns: 'Barons pris',
  blastConeOppositeOpponentCount:
    "Cônes explosifs utilisés contre l'adversaire",
  bountyGold: 'Or de prime récolté',
  buffsStolen: 'Buffs volés',
  completeSupportQuestInTime: 'Quête support terminée à temps',
  controlWardsPlaced: 'Balises de contrôle posées',
  damagePerMinute: 'Dégâts par minute',
  damageTakenOnTeamPercentage: "% des dégâts subis par l'équipe",
  dancedWithRiftHerald: 'Dansé avec le Héraut',
  deathsByEnemyChamps: 'Morts causées par des champions ennemis',
  dodgeSkillShotsSmallWindow: 'Skillshots esquivés de justesse',
  doubleAces: 'Double aces',
  dragonTakedowns: 'Dragons pris',
  effectiveHealAndShielding: 'Soin et bouclier effectifs',
  elderDragonKillsWithOpposingSoul:
    "Dragons anciens tués avec l'âme adverse active",
  elderDragonMultikills: 'Multi-kills grâce au dragon ancien',
  enemyChampionImmobilizations: 'Immobilisations infligées',
  enemyJungleMonsterKills: 'Monstres de la jungle adverse pris',
  epicMonsterKillsNearEnemyJungler:
    'Monstres épiques pris près du jungler adverse',
  epicMonsterKillsWithin30SecondsOfSpawn:
    "Monstres épiques pris dans les 30s après l'apparition",
  epicMonsterSteals: 'Monstres épiques volés',
  epicMonsterStolenWithoutSmite: 'Monstres épiques volés sans Châtiment',
  flawlessAces: 'Aces sans perte',
  fullTeamTakedown: "Ace complet de l'équipe adverse",
  gameLength: 'Durée de la partie',
  goldPerMinute: 'Or gagné par minute',
  hadOpenNexus: 'Nexus adverse mis à nu',
  immobilizeAndKillWithAlly: 'Immobilisation suivie d’un kill avec un allié',
  jungleCsBefore10Minutes: 'CS jungle avant 10 minutes',
  junglerTakedownsNearDamagedEpicMonster:
    "Éliminations du jungler près d'un monstre épique endommagé",
  kda: 'KDA (Riot)',
  killAfterHiddenWithAlly: "Kill après s'être caché avec un allié",
  killParticipation: 'Participation aux éliminations',
  killsNearEnemyTurret: 'Kills près de la tourelle adverse',
  killsOnOtherLanesEarlyJungleAsLaner:
    'Kills sur une autre lane en early (en tant que laner)',
  killsUnderOwnTurret: 'Kills sous sa propre tourelle',
  killsWithHelpFromEpicMonster: "Kills avec l'aide d'un buff de monstre épique",
  knockEnemyIntoTeamAndKill: "Ennemi propulsé dans l'équipe puis tué",
  kTurretsDestroyedBeforePlatesFall:
    'Tourelles détruites avant la chute des plaques',
  landSkillShotsEarlyGame: 'Skillshots touchés en début de partie',
  laneMinionsFirst10Minutes:
    'Sbires de lane tués dans les 10 premières minutes',
  lostAnInhibitor: 'Inhibiteur perdu',
  maxKillDeficit: 'Déficit de kills maximum',
  mejaisFullStackInTime: 'Mejai’s entièrement stackée à temps',
  moreEnemyJungleThanOpponent:
    "Plus de jungle adverse prise que l'adversaire jungler",
  multiKillOneSpell: 'Multi-kills avec un seul sort',
  multikills: 'Nombre total de multi-kills',
  multikillsAfterAggressiveFlash: 'Multi-kills après un flash agressif',
  multiTurretRiftHeraldCount: 'Tourelles multiples détruites par le Héraut',
  outerTurretExecutesBefore10Minutes:
    'Tourelles extérieures exécutées avant 10 minutes',
  outnumberedKills: 'Kills en infériorité numérique',
  outnumberedNexusKill: 'Nexus pris en infériorité numérique',
  perfectDragonSoulsTaken: 'Âmes de dragon parfaites obtenues',
  perfectGame: 'Partie parfaite',
  pickKillWithAlly: 'Pick réussi avec un allié',
  poroExplosions: 'Poros explosés',
  quickCleanse: 'Purification rapide',
  quickFirstTurret: 'Première tourelle rapide',
  riftHeraldTakedowns: 'Hérauts pris',
  saveAllyFromDeath: 'Allié sauvé de la mort',
  scuttleCrabKills: 'Crabes-crevettes pris',
  skillshotsDodged: 'Skillshots esquivés',
  skillshotsHit: 'Skillshots touchés',
  snowballsHit: 'Boules de neige touchées',
  soloBaronKills: 'Barons pris en solo',
  soloKills: 'Kills en solo',
  stealthWardsPlaced: 'Balises furtives posées',
  survivedSingleDigitHpCount: 'Survies avec moins de 10 PV',
  survivedThreeImmobilizesInFight:
    'Survies à 3 immobilisations dans un même combat',
  takedownOnFirstTurret: 'Participation à la première tourelle',
  takedowns: 'Nombre total d’éliminations (kills + assists)',
  takedownsAfterGainingLevelAdvantage:
    "Éliminations après avoir pris l'avantage de niveau",
  takedownsBeforeJungleMinionSpawn:
    "Éliminations avant l'apparition des monstres de jungle",
  takedownsInEnemyFountain: 'Éliminations dans la fontaine adverse',
  teamBaronKills: "Barons pris par l'équipe",
  teamDamagePercentage: "% des dégâts totaux de l'équipe",
  teamElderDragonKills: "Dragons anciens pris par l'équipe",
  teamRiftHeraldKills: "Hérauts pris par l'équipe",
  tookLargeDamageSurvived: 'Gros dégâts subis et survécu',
  turretPlatesTaken: 'Plaques de tourelle prises',
  turretsTakenWithRiftHerald: 'Tourelles prises avec le Héraut',
  turretTakedowns: 'Tourelles prises',
  twentyMinionsIn3SecondsCount: '20 sbires tués en 3 secondes',
  unseenRecalls: 'Rappels effectués sans être vu',
  visionScorePerMinute: 'Score de vision par minute',
  wardsGuarded: 'Wards protégées',
  wardTakedowns: 'Wards détruites',
  wardTakedownsBefore20M: 'Wards détruites avant 20 minutes',
}

/**
 * Human-readable French label for a `LoLGameParticipantChallengesDto` field
 * name, used by the raw stats table.
 */
export function challengeFieldLabel(key: string): string {
  const label = CHALLENGE_FIELD_LABELS[key]

  if (label != null) {
    return label
  }

  const spaced = key
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/([a-zA-Z])([0-9])/g, '$1 $2')
    .replace(/([0-9])([a-zA-Z])/g, '$1 $2')

  return spaced.charAt(0).toUpperCase() + spaced.slice(1)
}
